### ISSUE TITLE
apt-cacher-ng stopped working ( 2016-01-01 )

### ISSUE THREAD

**Issue by dlarue** [mariolukas/FabScanPi-Build-Raspbian#1]
I'm not seeing changed to apt-cacher-ng status of hits/misses as I did in the previous build. Maybe the cacher changes of a day or two ago didn't make it into the latest updates?

FYI, I liked seeing the fabscan packages in the image build process. :+1:

**Comment by mariolukas** [comment]
fixed in the current master branch
