### ISSUE TITLE
Fix trap and loop device issue 

### ISSUE THREAD

**Issue by mariolukas** [mariolukas/FabScanPi-Build-Raspbian#10]
Adding the following lines should fix the loop device issue and give more detailed logging. 

```
script="build_raspbian_sd_card.sh"
# rotate  logfiles
#
logfile="/var/log/build_rpi_wheezy_sd_card"
   [ -f "$logfile.4" ] && mv -f "$logfile.4" "$logfile.5"
   [ -f "$logfile.3" ] && mv -f "$logfile.3" "$logfile.4"
   [ -f "$logfile.2" ] && mv -f "$logfile.2" "$logfile.3"
   [ -f "$logfile.1" ] && mv -f "$logfile.1" "$logfile.2"
   [ -f "$logfile"   ] && mv -f "$logfile"   "$logfile.1"

# clear loop devices opened by previous runs of this script.
# The command losetup -a prints used loop devices like this (1 line per device)
# 
# /dev/loop0: [fc00]:14039433 (/root/rpi/rpi_basic_wheezy_20170129.img)
#

# print status of loop device related stuff...
#
lo_status()
{
loop_count=`losetup -a | grep -c rpi_basic_wheezy`
if [ $loop_count -eq 0 ]; then
   echo "there are no open loop devices (good). "
   return 0
fi

echo "
*** there is/are $loop_count open loop device(s):
"
   losetup -a

echo "
mtab says:
----------"
grep loop /etc/mtab

echo "
mount says:
-----------"
mount | grep loop

echo "
loop devices in /dev are:
-------------------------"
ls -l /dev/ | grep loop

echo "
loop devices in /dev/mapper are:
--------------------------------"
ls -l /dev/mapper | grep loop
}

unmount_loop_devices()
{
loop_count=`losetup -a | grep -c rpi_basic_wheezy`
if [ $loop_count -eq 0 ]; then
   echo "unmount_loop_devices() : no stale devices detected (good)/"
   return 0
fi

loop_devices=`losetup -a | grep rpi_basic_wheezy \
                         | awk -F: '{print $1;}'`
   lo_status

for f in "$loop_devices"; do
    echo "
    *** closing stale loop device $f..."
    echo "
           DM partition 1
           --------------"
    set -x
    dmsetup info /dev/mapper/loop0p1
    umount -v -f -d /dev/mapper/loop0p1
    echo "umount returned $?"
    dmsetup info /dev/mapper/loop0p1
    sleep 1
    dmsetup -f remove /dev/mapper/loop0p1
    echo "dmsetup -f remove /dev/mapper/loop0p1 returned $?"
    set +x

echo "*** device is $f..."
    echo "
           DM partition 2
           --------------"
    set -x
    dmsetup info /dev/mapper/loop0p2
    umount -v -f -d /dev/mapper/loop0p2
    echo "umount returned $?"
    dmsetup info /dev/mapper/loop0p2
    sleep 1
    dmsetup -f remove /dev/mapper/loop0p2
    echo "dmsetup -f remove /dev/mapper/loop0p2 returned $?"

echo "*** device is $f..."
    losetup -d "$f"
    lo_result=$?
    if [ $lo_result -ne 0 ]; then
       ls -l /dev/ |grep loop
       ls -l /dev/mapper/
    fi
    echo "losetup returned $lo_result"
    set +x
done

loop_count=`losetup -a | grep -c rpi_basic_wheezy`
if [ $loop_count -eq 0 ]; then
   echo "
all stale loop devices could be removed
"
   return 0
fi

# at this point something went wrong. Collect information

   echo "
closing all stale loop devices failed. The status is:
"
   lo_status
}

control_C()
{
   set +x
   echo "
got ^C"
   unmount_loop_devices
}

build_image()
{

.... script main part here ....



echo "finishing ${image}"
#clean_uptrap
unmount_loop_devices
echo $script done at `date`
}


build_image 2>&1 | tee $logfile 2>&1

```

**Comment by PhistterbutInc** [comment]
I've just come across the error involving loop device while building from script. Where would this code be placed to fix the issue?

I'm using VMware workstation to run ubuntu 18.04lts and build this script. Initially I had allocated too little storage and increased it later. I'm not sure if that's an issue or not.

Error: (the full log of output is much too long, this is the end)

Device                                                                        Boot  Start     End Sectors  Size Id Type
/pi-gen/work/2019-08-01-FabScanPi/export-image/2019-08-01-FabScanPi-lite.img1        8192  532480  524289  256M  c W95 FAT32 (LBA)
/pi-gen/work/2019-08-01-FabScanPi/export-image/2019-08-01-FabScanPi-lite.img2      540672 4300799 3760128  1.8G 83 Linux

Command (m for help): The partition table has been altered.
Syncing disks.

losetup: /pi-gen/work/2019-08-01-FabScanPi/export-image/2019-08-01-FabScanPi-lite.img: failed to set up loop device: No such file or directory

real	76m12.174s
user	0m0.323s
sys	0m0.792s

**Comment by mariolukas** [comment]
This issue should be closed, cause this is not related to the new version of the build script since I switched to using the original pi-gen build script. 
Anyway your issue seems to be similar. I would try to build a plain raspbian with pi-gen only. If this works the error is fabscan related. If it not works the loop device problem is a general problem of the build script and you should create an issue in the [pi-gen](https://github.com/RPi-Distro/pi-gen) project. 
I don't know how Ubuntu handles loop devices in a VMWare session.

**Comment by mariolukas** [comment]
I changed the bash script. It will checkout the latest stable version ( currently buster build ) of pi-gen. This should prevent breaking changes in the master branch. 
Maybe the README.md was also wrong. Try to use 

`sudo  ./build-fabscan.sh`

instead of 

` ./build-fabscan.sh`

Maybe this will fix the error because the default ubuntu user is not able to handle loop devices.

**Comment by PhistterbutInc** [comment]
I did use sudo ./build-fabscan.sh.  I'll try building an image like you suggest and see what happens.

**Comment by mariolukas** [comment]
This issue is related to https://github.com/mariolukas/FabScanPi-Build-Raspbian/issues/15
