### ISSUE TITLE
issue: Scan Freezes after Texture scanning

### ISSUE THREAD

**Issue by tpipits** [mariolukas/FabScanPi-Build-Raspbian#16]
Hello.
I try to build my own diy version of fabscan but i have connection problems.
------------------------------------------------------------------------------
I can use an arduino pro micro (atmega32u4) and my diy hat (based an fabscan uno hat schematics) with one stepper and two lasers only and pi noir cam with adjustable focus connected to pi via usb.
------------------------------------------------------------------------------
With arduino pro micro i have compile/upload with IDE your firmware (from: https://github.com/mariolukas/FabScanPi-Firmware) and the changes i have made as follow:

a. boards.h:
#ifndef BOARDS_H
#define BOARDS_H
//#define BOARD_UNKNOWN -1
//#define BOARD_FABSCANPI             1    
//#define BOARD_CYCLOP                2
//#define BOARD_SANGOINOLOLU          3
//#define BOARD_CNCSHIELD             4
#define BOARD_PIPITS                5
#define MB(board) (MOTHERBOARD==BOARD_##board)
#endif

b. configuration.h
// FabScan - http://hci.rwth-aachen.de/fabscan
//
//  Created by Mario Lukas on 04/08/14.
//  Copyright 2014 Media Computing Group, RWTH Aachen University. All rights reserved.
//
//#define VERBOSE 0
// You can use an online service to generate a random UUID. (eg http://www.uuidgenerator.net/version4)
//#define MACHINE_UUID "4dabfe2e-c094-4f04-8bd4-669f24460735"
#ifndef CONFIGURATION_H
#define CONFIGURATION_H
/*
 * The following define selects which electronics board you have.
 * Please choose the name from boards.h that matches your setup.
 * Some possible Values are:
 *
 * BOARD_FABSCANPI    - FabScanPi Hat for Raspberry Pi
 * BOARD_CYCLOP       - Cyclop Scanner ZUM Scan Board
 * BOARD_SANGUINOLOLU - Sanguinololu 3D Printer Board v 1.3
 * BOARD_CNCSHIELD - Arduino Uno with CNC shield V3.0 or newer (see grbl project for pinout)
 *
 */
#ifndef MOTHERBOARD
  #define MOTHERBOARD BOARD_PIPITS
#endif
#ifndef BAUDRATE
  #define BAUDRATE 115200
#endif
#define TURN_BLOCKING 1
#define TURN_NON_BLOCKING 0
#define NUMPIXELS 16
#define MAX_FEEDRATE         (2000)
#define MIN_FEEDRATE         (1000)
#define MAX_BUF        64
#endif

c.pins.h
#ifndef __PINS_H__
#define __PINS_H__
#if MB(FABSCANPI)
  #include "pins_FABSCANPI.h"
#elif MB(CYCLOP)
 #include "pins_CYCLOP.h"
#elif MB(SANGOINOLOLU)
 #include "pins_SANGOINOLOLU.h"
#elif MB(CNCSHIELD)
 #include "pins_CNCSHIELD.h"
#elif MB(PIPITS)
 #include "pins_PIPITS.h"
#endif
#endif

d.pins_PIPITS.h
#ifndef PINS_PIPITS_H
#define PINS_PIPITS_H
#ifndef BOARD_NAME
  #define BOARD_NAME "PIPITS"
#endif
/*
 * Laser 
 */
#define RIGHT_LASER_PIN 8
#define LEFT_LASER_PIN 9
#define MICROSTEP   A10
/*
 * Turntable Stepper
 */
#define ENABLE_PIN_0  21
#define STEP_PIN_0    20
#define DIR_PIN_0     19
/**
 * WS2812 LED 
 */
#define LIGHT_PIN A6
/**
 * Optional Laser Stepper
 */
#define ENABLE_PIN_1  5
#define STEP_PIN_1    6
#define DIR_PIN_1     7
 /**
  * Optional Laser Servos
  */
#define RIGHT_SERVO_PIN 14
#define LEFT_SERVO_PIN 16
/**
 *  STEPPER DEFINES FOR SELECTION
 */
#define LASER_STEPPER        2  //0xb
#define TURNTABLE_STEPPER    3  //0xa
#endif
------------------------------------------------------------------------------
So i have try with both latest version of prebuild image (0.94server and 0.93server)
and when i use the commands "sudo echo "M19" > /dev/ttyACM0" or "sudo echo "M19" > /dev/serial/by-id/usb-Arduino_LLC_Arduino_Micro-if00" at terminal (i can use all of the commands M and G) the system works as expected (laser on/off, motor disable/enable, motor running). (PiOS read device as /dev/ttyACM0 and not as /dev/ttyUSB0).
--------------P R O B L E M-------------------------------------------------
BUT the server not running with the following problems from log file (changes made only to etc folder at file default.config.json) :

1. if i use:
   "serial": {
        "plattform_type": "pipits",
        "baudrate": 115200,
        "autoflash": "False",
        "port": "/dev/serial/by-id/usb-Arduino_LLC_Arduino_Micro-if00",
        "flash_baudrate": 115200

2021-03-04 09:38:20,098 [521:1996384976] INFO - fabscan.server.FSScanServer: FabScanPi-Server 0.9.3
2021-03-04 09:38:20,106 [521:1996384976] DEBUG - fabscan.scanner.interfaces: Scanner Type is: laserscanner
2021-03-04 09:38:21,948 [521:1996384976] DEBUG - fabscan.scanner.laserscanner.driver.FSSerial: Port in Config found
2021-03-04 09:38:21,953 [521:1996384976] CRITICAL - fabscan: Fatal error: max() arg is an empty sequence
(which seems that connection made but sth is missing) 

2. if i use:
   "serial": {
        "plattform_type": "pipits",
        "baudrate": 115200,
        "autoflash": "False",
        "port": "/dev/ttyACM0",
        "flash_baudrate": 115200

2021-03-04 09:38:20,098 [521:1996384976] INFO - fabscan.server.FSScanServer: FabScanPi-Server 0.9.3
2021-03-04 09:38:20,106 [521:1996384976] DEBUG - fabscan.scanner.interfaces: Scanner Type is: laserscanner
2021-03-04 09:38:21,948 [521:1996384976] DEBUG - fabscan.scanner.laserscanner.driver.FSSerial: Port in Config found
2021-03-04 09:38:21,953 [521:1996384976] CRITICAL - fabscan: Fatal error: max() arg is an empty sequence
(which seems that connection made but sth is missing) 

3. if i use:
   "serial": {
        "plattform_type": "fabscanpi or ciclop",
        "baudrate": 115200,
        "autoflash": "False",
        "port": "/dev/ttyACM0",
        "flash_baudrate": 115200

2021-03-04 09:45:44,474 [685:1995705040] INFO - fabscan.server.FSScanServer: FabScanPi-Server 0.9.3
2021-03-04 09:45:44,478 [685:1995705040] DEBUG - fabscan.scanner.interfaces: Scanner Type is: laserscanner
2021-03-04 09:45:45,450 [685:1995705040] DEBUG - fabscan.scanner.laserscanner.driver.FSSerial: Port in Config found
2021-03-04 09:45:45,452 [685:1995705040] DEBUG - fabscan.scanner.laserscanner.driver.FSSerial: Latest available firmware version is: v.20200624
2021-03-04 09:45:47,016 [685:1995705040] ERROR - fabscan.scanner.laserscanner.driver.FSSerial: Communication error on port /dev/ttyACM0 try other flashing baudrate than 115200. Maybe corrupted bootloader.
2021-03-04 09:45:47,017 [685:1995705040] ERROR - fabscan.scanner.laserscanner.driver.FSSerial: Fatal FabScanPi HAT or compatible connection error: 'NoneType' object has no attribute 'isOpen'
2021-03-04 09:45:47,017 [685:1995705040] INFO - fabscan.server.FSScanServer: FabScan Server Exit. Bye!
(which seems that connection made but a lot of things are wrong, so i beleive this is the wrong approach and i have to used the setup no.1 or no.2 (maybe no.1 because then there is no matter in which port the arduino will be connected) where the server just stuck and not exit).
--------------Q U E S T I O N-------------------------------------------------
What i miss in my configuration and the server not running???
What else i have to add/change for fabscan to read my hardware???

If i success i can give you all of the setup for arduino pro micro to update the setup/config files.
I 'm waiting for your response.
Thnks.

**Comment by mariolukas** [comment]
Hi, 

a new custom solution sounds great to me. But can you please open a development topic in the forum on fabsca.org. You can just copy the content of the issue to the forum.  It is better to discuss this in the Forum, cause it affects different parts of the system (Firmware, Server,  maybe OS). This issue Tracker is more for bug reports. Your issue is more a general development topic. And even other users might find this useful in the forum. You can use a Topic title like "How can i use a custom Arduino wiring" or something similar. 

Thanks 
- Mario

**Comment by tpipits** [comment]
I 'm coming back with partial solution.
Finally i have made it work with just changing one letter at FSSerial.py so i don't need the check for avr device and i am able now to use pro micro as fabscan pi processor.

--------------original--------------------------------------------------
    def avr_device_is_available(self):
        status = FSSystem.run_command("sudo avrdude-autoreset -p m328p -b {0} -carduino -P{1}".format(self.flash_baudrate, self._port))
        return status == 0
--------------change---------------------------------------------------
        return status != 0
------------------------------------------------------------------------

Also you have to set firmaware upgrade to false at default.config.json.
Now i run my DIY scanner (copy of cyclop) with 2 laser, pi cam v1 NoIR, raspberry pi 4b 2gb, ws2812b 24bit rgb led, pro micro (usb connection - 115200 baudrate).
The server starts.
I am able to change camera settings, led settings, on/off camera/laser 1&2/turntable CW direction.
I have made calibration with success, but the rgb led don't turn ON at calibration (i don't know why, and i think that calibration wants led lighting). Cam, lasers and turntable works as expected.
Then i try to start a scan and here i have problem.
The first part of scanning proccess run ok (texture scan).
The second part, or if i choose scan without color stucks and nothing happens, no picture of cam, no laser on/off, no turntable turning. The server freeze, the pi won't reboot from putty and i have to remove the power plug to restart.
i have tried with two images (0.9.4 stable from repository, upgrade then from testing repository to later version) with the same results.
I attached two photo and my log file (scan time from 11:17:08,270 to 2021-04-16 12:07:08,191).
Please i wait for your answer form my two problems:
1. Why RGB Led ring not power on at calibration?
2. Why the scan proccess stucks at laser scanning?
Thank you.

![1](https://user-images.githubusercontent.com/58324222/115020640-8c06cf80-9ec3-11eb-8e81-25081cd8622e.jpg)
![2](https://user-images.githubusercontent.com/58324222/115020645-8dd09300-9ec3-11eb-82ea-f343ab116f91.jpg)
[logfile.txt](https://github.com/mariolukas/FabScanPi-Build-Raspbian/files/6324695/logfile.txt)

**Comment by tpipits** [comment]
After a lot of troubleshooting i made o downgrade to version 0.9.3+202008272250 as suggested here:
https://fabscan.org/community/latest-release/easy-change-of-the-version/#post-1742
Nothing works again....
Suddenly server made an automatic update to v0.9.4 (i think is stable because there is no + after) and as a kind of magic all works as expexted.....
The calibration runs with light, and the scan finished with textured and two lasers as expected. Object saved and can be upload to  pc. 
I don't know what happened, but now works as expected....
